export {default as EditableInput} from "./EditableInput.vue"
export {default as EditableTextarea} from "./EditableTextarea.vue"
export {default as EditableSelect} from "./EditableSelect.vue"
export {default as EditableCheckboxPlugin} from "./EditableCheckbox.vue"
export {default as EditableRating} from "./EditableRating.vue"